### ISSUE TITLE
ConvertContext doesn't support object-form context

### ISSUE THREAD

**Issue by warriordog** [Letterbook/Letterbook.ActivityPub#21]
Unfortunately, it is possible to construct a cursed (but valid!) ActivityPub object of this shape:
```json
{
  "@context": {
    "@import": "https://www.w3.org/ns/activitystreams"
  },
  "type": "Note",
  "...": "etc"
}
```
This will crash [ConvertContext](https://github.com/Letterbook/Letterbook.ActivityPub/blob/main/Letterbook.ActivityPub/ConvertContext.cs) as it only handles objects when they are elements of an array. I don't *think* anyone is doing this in practice, but I can imagine a scenario where some JSON-LD tooling tries to "optimize" the context by merging everything down. See this for more info about `@import`: https://www.w3.org/TR/json-ld11/#imported-contexts.

**Comment by jenniferplusplus** [comment]
Thank you!

Sorry to be slow about responding, I haven't gotten issue notifications worked out on these repos yet

**Comment by warriordog** [comment]
@jenniferplusplus no worries at all! I just wanted to make sure you knew about this, since I was skimming the code and happened to noticed that `ConvertContext` had the same mistake I'd previously made.

Would you be interested in more issues of this type (cursed AP message samples that break parsing)? I've found some pretty horrendous edge cases that I'd be glad to share, but I don't want to just show up with a bunch of issues like "hey, this breaks your code haha" 😅

**Comment by warriordog** [comment]
@jenniferplusplus related question, would you accept PRs to fix such edge cases?

**Comment by jenniferplusplus** [comment]
Yes to both, if you feel up to it. I want these projects to be welcoming to new contributors, but it's hard with everything in such an early state

**Comment by warriordog** [comment]
@jenniferplusplus cool, I'll take a shot at this 👍

**Comment by warriordog** [comment]
@jenniferplusplus for unit tests, do you mind if I add an assertion library like FluentAssertions? Or do you prefer tests be more manual?
